### ISSUE TITLE
Not working Properly

### ISSUE THREAD

**Issue by AnishBashist** [termux/termux-api-package#108]
**Problem description**
A clear and concise description of what the problem with termux-api-package is. You may post screenshots or paste error messages in addition to description.

**Steps to reproduce**
Please post all steps that are needed to reproduce the issue.

**Expected behavior**

**Additional information**
Post output of command `termux-info`.
If you are rooted or have access to adb then capture a logcat with `logcat -d "*:W"`, from a adb or root shell.

**Comment by Grimler91** [comment]
Well we can't fix a problem without knowing what the problem is. Please fill in the bug report template.
