### ISSUE TITLE
l want to speak turkish with termux but termux-speech-to-text can only understand english

### ISSUE THREAD

**Issue by kaankarakoc42** [termux/termux-api-package#112]
l cant use the termux-speech-to-text  with turkish

**Comment by xeffyr** [comment]
Have you checked your text-to-speech configuration in Android settings?

**Comment by kaankarakoc42** [comment]
Text-to-speech is working in another languages but speech-to-text only can works on english.My problem is  speech-to-text api

**Comment by kaankarakoc42** [comment]
> Have you checked your text-to-speech configuration in Android settings?

Text-to-speech is working in another languages but speech-to-text only can works on english.My problem is speech-to-text api

**Comment by kaankarakoc42** [comment]
Termux can speaking Turkish but can't understand Turkish words is it possible to fix that problem? or is it just working like this?

**Comment by Benjamin-Loison** [comment]
Have you achived to solve this issue @kaankarakoc42?
