### ISSUE TITLE
Termux-telephony-call ignores # sign

### ISSUE THREAD

**Issue by 0Karakurt0** [termux/termux-api-package#133]
**Problem description**
I had an idea to try and automate balance checking, so I tried calling *112# (right one for me)
But my telephony app received only *112.
When I tried to escape hash sign that app received *112\\
And when I tried taking directly to termux-api, I got  `Error: Argument expected after "*112#"` message with process hanging (Ctrl+c finished)

**Steps to reproduce**
Call any number containing # sign

**Expected behavior**
To be able to call a number containing # sign  

**Additional information**
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# game-repo (sources.list.d/game.list)
deb https://grimler.se/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://grimler.se/science-packages-24 science stable
# root-repo (sources.list.d/root.list)
deb https://grimler.se/termux-root-packages-24 root stable
# x11-repo (sources.list.d/x11.list)
deb https://ipfs.io/ipns/k51qzi5uqu5dgu3homski160l4t4bmp52vb6dbgxb5bda90rewnwg64wnkwxj4 x11 main
Updatable packages:
apt/stable 2.3.3 aarch64 [upgradable from: 2.2.2]
bash/stable 5.1.8 aarch64 [upgradable from: 5.1.4]
clang/stable 12.0.0 aarch64 [upgradable from: 11.1.0]
dpkg/stable 1.20.9 aarch64 [upgradable from: 1.20.7.1-1]
feh/x11 3.6.3-2 aarch64 [upgradable from: 3.6.3-1]
file/stable 5.40 aarch64 [upgradable from: 5.39-1]
gdk-pixbuf/stable 2.42.6 aarch64 [upgradable from: 2.42.2]
gpgv/stable 2.3.1-1 aarch64 [upgradable from: 2.2.27-1]
harfbuzz/stable 2.8.1 aarch64 [upgradable from: 2.8.0]
imagemagick/stable 7.0.11.10 aarch64 [upgradable from: 7.0.11.1]
krb5/stable 1.19.1 aarch64 [upgradable from: 1.19]
libedit/stable 20210419-3.1-0 aarch64 [upgradable from: 20191231-3.1-1]
libgcrypt/stable 1.9.3 aarch64 [upgradable from: 1.9.1]
libgpg-error/stable 1.42 aarch64 [upgradable from: 1.41]
libjpeg-turbo/stable 2.1.0 aarch64 [upgradable from: 2.0.6]
libllvm/stable 12.0.0 aarch64 [upgradable from: 11.1.0]
librsvg/stable 2.50.5 aarch64 [upgradable from: 2.50.3]
libsqlite/stable 3.35.5 aarch64 [upgradable from: 3.34.0-1]
libtiff/stable 4.3.0 aarch64 [upgradable from: 4.2.0]
nano/stable 5.7 aarch64 [upgradable from: 5.6.1]
oniguruma/stable 6.9.7 aarch64 [upgradable from: 6.9.6]
openssh/stable 8.6p1 aarch64 [upgradable from: 8.4p1-2]
pango/stable 1.48.4 aarch64 [upgradable from: 1.48.1]
python/stable 3.9.5 aarch64 [upgradable from: 3.9.4]
readline/stable 8.1.1 aarch64 [upgradable from: 8.1.0]
termux-api/stable 0.56 aarch64 [upgradable from: 0.54]
termux-tools/stable 0.119 all [upgradable from: 0.118]
util-linux/stable 2.36.2 aarch64 [upgradable from: 2.36.1]
x11-repo/stable 7.0 all [upgradable from: 6.0]
Android version:
11
Kernel build information:
Linux localhost 4.14.228-VantomKernel #1 SMP PREEMPT Thu Apr 1 12:21:02 UTC 2021 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
Mi 9T

**Comment by agnostic-apollo** [comment]
Thanks for the report. Fixed by termux/termux-api@2d7672c. Will require Termux:API app update.
