### ISSUE TITLE
termux-notification: what are actions?

### ISSUE THREAD

**Issue by pawamoy** [termux/termux-api-package#37]
I had difficulty to understand how I'm suppose to use termux-notification actions. Are they commands I can run in the shell? Like a full command? Or only an executable name, available on the PATH?

I tried running
- `echo hello | termux-notification --action "echo hi"`
- `echo hello | termux-notification --action echo`
- `echo hello | termux-notification --action ls`

...with no luck, but finally got it with
```
echo hello | termux-notification --action "touch f"
```
...and `f` was touched if I tapped on the notification.

A note explaining actions before options would be great! I can open a PR but english is not my native language, so others might phrase it better.

**Comment by ulist** [comment]
also

**Comment by ulist** [comment]
No it's work fine check the running programs
execute 'ps' or 'top'

**Comment by pawamoy** [comment]
Yes, it works fine. I never said it was not working though :wink: 

I'm just saying that it should be explained that the action is a string, executed as a command in a subprocess when the user taps on the notification.

**Comment by ulist** [comment]
Not even issue
before I go do you want a hug?

**Comment by pawamoy** [comment]
I'll just say I'm not sure to understand the tone you're using.

**Comment by andb0t** [comment]
Related to this: how could I make a tap on the notification focus the termux window? Is there an example somewhere?

By the way, great work with the termux-api. I love it :)

**Comment by xalexalex** [comment]
@pawamoy I agree that some info on the quirks of `--action` may help many users. The things that are worth documenting, in my opinion, are at least these:

- you should use actions that do things outside of the terminal, like `--action "termux-toast hello"`. Anything that outputs to the terminal is useless, so the output should either be redirected (`--action "ls > ~/ls.txt"`) or shown to the user in a different way (`--action "ls|termux-toast"`).
- The argument to `--action` is fed to `dash -c`, so you don't need escaping or wizardry to run more than one command, it's as easy as `--action "this; that; another"` or `--action "if [ -e file ]; then termux-toast yes; else termux-toast no; fi"`.
- for anything more complex, you should put your script in a file, make it executable, and just `--action ~/bin/script`.
- `--action` invokes `dash` in a *different* environment (not a subshell). Thus your environment is lost (most notably `$PATH`), and `~/.profile` is not sourced either. So if you need your `$PATH` you should either
    - set it explicitly in the script (e.g. `export PATH="$HOME/bin:$PATH"`)
    - or use something like `--action "bash -l -c 'this; that'")

Apologies for any mistakes (it's 1AM here).

Feel free to add something (even in French).

Later we'll decide on the appropriate place for this info. I would like to avoid cluttering `termux-notification -h`, so I'd either put it in the wiki or in `termux-notification --action-help`.

**Comment by pawamoy** [comment]
@xalexalex it's exactly the kind of info I was looking for 😀 I think it would be perfect to have an `--action-help` or `--help-action` flag, mirrored in the wiki of course.

**Comment by xalexalex** [comment]
Okay, the draft is now accessible with `termux-notification --help-actions` (in termux-api-package v0.46) and will soon be in the wiki. Please feel free to reopen this issue or draft a pull request to change the text.
