### ISSUE TITLE
Hashtag on Telephony Call

### ISSUE THREAD

**Issue by killouis** [termux/termux-api-package#4]
Hi,
i'm trying to schedule the change of the call-forwarding of my phone using Termux-Api Telephony Call.
The problem i'm facing is that i want to call a number composed by hashtag, here is an example:

> termux-telephony-call **21\*+391234567890#

When i try to use this command, the phone call the number  **21\*+391234567890 and loses the hashtag.
Can anyone help me?
Thanks

**Comment by Neo-Oli** [comment]
Try putting the number in single quotes 
```
termux-telephony-call '**21*+391234567890#' 
```

**Comment by killouis** [comment]
Hi,
thank you for your response.
I've tryed but unfortunately it doesn't work.
Any suggestions?

**Comment by pizzapants184** [comment]
You need to encode the '#'  as '%23', so your command would be `termux-telephony-call '**21*+391234567890%23' .

[Source](https://stackoverflow.com/questions/13593970/what-is-the-difference-between-uri-escape-and-uri-encode-in-ruby)

**Comment by killouis** [comment]
Hi,
thank you very much for your response.
It work now!!!
