### ISSUE TITLE
termux-dialog not working

### ISSUE THREAD

**Issue by srajasimman** [termux/termux-api-package#49]
Hi,

the termux-dialog is not working on my andoird p device. when I used android 8 it works perfectly and now I am using android 9. termux-dialog is just frozen after entering any dialog option.
with termux-dialog I created a small utility to download media files. now the utility is totally useless without termux-dialog tool.

My Device Info:
Updatable packages: All packages up to date
System information: Linux localhost 4.4.153-perf+ #1 SMP PREEMPT Tue Jan 15 18:34:25 WIB 2019 aarch64 Android
Termux-packages arch: aarch64
Android version: 9
Device manufacturer: Xiaomi
Device model: Mi A2

**Comment by laconbass** [comment]
See also https://github.com/termux/termux-api/issues/228
