### ISSUE TITLE
termux-notification not showing full message!

### ISSUE THREAD

**Issue by gustavohornig** [termux/termux-api-package#57]
Hey guys! I'm doing a simple .py file to run some os.system("termux-notification ..."). Anyway, I'm using something like this:

"termux-notification -t 'This is a huge test so you guys can understand my situation with the notification'". 

So, when I execute it, my notification comes like this:

"This is a huge test so you guys ..."

It doesn't show the FULL notification. Is there anyway I could solve it? Thanks

**Comment by xeffyr** [comment]
Android may not allow big notifications.
