### ISSUE TITLE
dialog confirm - Too many arguments!

### ISSUE THREAD

**Issue by 0xACE** [termux/termux-api-package#58]
```
$ termux-dialog confirm "Simple Test"
ERROR: Too many arguments!
Usage: termux-dialog widget [options]
Get user input w/ different widgets! Default: text
   -h, help   Show this help
   -l, list   List all widgets and their options
   -t, title  Set title of input dialog (optional)
```

Or am I using it wrong?

**Comment by dkramer95** [comment]
@0xACE If you want "Simple Test" to be the title, then you can call using: 
`termux-dialog confirm -t "Simple Test"`
There is also a default placeholder "Confirm" text that will be shown, which can be customized by passing argument with "-i" option. To remove, just pass an empty string as such:
`termux-dialog confirm -c "Simple Test" -i ""`
For detailed usage of all possible widgets call:
`termux-dialog -l`

**Comment by 0xACE** [comment]
Thanks, yeah I was using this wrong. My bad.
