### ISSUE TITLE
Using termux api inside a linux distro

### ISSUE THREAD

**Issue by sujitvasanth** [termux/termux-api-package#59]
Hi. termux api works great out of the box from inside the termux terminal.
I want to use termux api commands from inside a kali-linux distro that in in termux (anLinux)
specifically i wanted to do this from inside python running in the distro.
is this possible?

thanks

Sujit

**Comment by Oj18** [comment]
All the binaries / scripts are located here: `/data/data/com.termux/files/usr/bin/` so you may just be able to call them from there.

Example for notifications:
`/data/data/com.termux/files/usr/bin/termux-notification -t "Test" -c "Basic test"`

`echo -e "Test with\nMultiline" /data/data/com.termux/files/usr/bin/termux-notification -t "Test"`

**Comment by q-codes** [comment]
> All the binaries / scripts are located here: `/data/data/com.termux/files/usr/bin/` so you may just be able to call them from there.
> 
> Example for notifications:
> `/data/data/com.termux/files/usr/bin/termux-notification -t "Test" -c "Basic test"`
> 
> `echo -e "Test with\nMultiline" | /data/data/com.termux/files/usr/bin/termux-notification -t "Test"`

NO! It does not work....without being root. Outside of termux, say, from an external terminal emulator, it does not work:
`not found` or `permission denied`

What to do to? [very-worried-emoji][thinking-emoji]x2

**Comment by xeffyr** [comment]
> Outside of termux, say, from an external terminal emulator, it does not work

Yes, external applications can't access the Termux file system directly. Note that this issue is not about your case but about using Termux:API from the proot'ed Linux distro.

**Comment by xeffyr** [comment]
Closing as in https://github.com/termux/proot/issues/23 is shown what is needed to use am, termux-api and other Termux commands from proot'ed distribution.
