### ISSUE TITLE
error make

### ISSUE THREAD

**Issue by emporeso2** [termux/termux-api-package#67]
Got this error when i compile:

`cc -std=c11 -Wall -Wextra -pedantic -Werror    termux-api.c   -o termux-api
termux-api.c: In function ‘generate_uuid’:
termux-api.c:71:13: error: implicit declaration of function ‘arc4random’; did you mean ‘srandom’? [-Werror=implicit-function-declaration]
             arc4random(), arc4random(),                 // Generates a 64-bit Hex number
             ^~~~~~~~~~
             srandom
cc1: all warnings being treated as errors
make: *** [<builtin>: termux-api] Error 1`

**Comment by xeffyr** [comment]
Because it can be compiled only with [patched](https://github.com/termux/termux-packages/tree/master/ndk-patches) Android NDK.
