### ISSUE TITLE
No option for ongoing (sticky) notifications

### ISSUE THREAD

**Issue by xeffyr** [termux/termux-api-package#70]
NotificationAPI already implemets support for ongoing notifications: https://github.com/termux/termux-api/blob/master/app/src/main/java/com/termux/api/NotificationAPI.java#L79.

But related option is not present in the wrapper script (termux-notification).

**Comment by Oj18** [comment]
Just an fyi, in a pull request I did a while ago I slightly broke something in notifications, so I'll add this whilst fixing that hopefully. (Going to make a separate issue for it.)

**Comment by xalexalex** [comment]
Fixed by #72

**Comment by fornwall** [comment]
Thanks @xalexalex !
