### ISSUE TITLE
Looking for maintainers!

### ISSUE THREAD

**Issue by fornwall** [termux/termux-api-package#76]
It would be nice to get one or several maintainers that can merge PR:s, close issues and make releases.

@xalexalex, do you want to?

**Comment by xalexalex** [comment]
Sure, I would be honored!

One question: approximately half of the open issues on this repo actually belong to termux/termux-api. Would it be ok for you if I moved them to the correct repo, or do you prefer to keep them here (perhaps with a `termux-api` tag)?

**Comment by fornwall** [comment]
@xalexalex Great! I've added you as an admin for this repo and for https://github.com/termux/termux-api!

I think it's a good idea to move the issues to the right repo.

You're welcome to join https://gitter.im/termux/dev to chat with other Termux developers!
